# NOTE: THE ORDER OF THE FOLLOWING LIST IS IMPORTANT

geo = [
    'Total',
    'CP',
    'Faisalabad',
    'Gujranwala',
    'Jhang',
    'Lahore',
    'SP',
    'Bahawalpur',
    'D.G.Khan',
    'Multan',
    'Sahiwal',
    'NR',
    'Islarea',
    'islrwlmarket',
    'islmarket',
    'rwlmarket',
    'Sargodha',
    'North A',
    'Peshawar',
    'Jhelum',
    'S&B',
    'Quetta',
    'Hyderabad',
    'Karachi',
    'Nawab Shah',
    'Sukkur',
    'Rest of Urban',
    'LRG-Rural',
    'MED-Rural',
    '10KC','4Metros',
    'Punjab',
    'Sind',
    'Sind NK',
    'KPAJK',
    'Balochistan',
    'Urban Grocery',
    'Urban Pay & Go',
    'Urban Entertainment',
    'DPS',
    'Kiryana',
    'Pan',
    'Kiosk',
    'Hotels'
    ]
